### ISSUE TITLE
workflow of GAP-RSS

### ISSUE THREAD

**Issue by MengnanCui** [libAtoms/workflow#214]
Hi, I am trying to follow the workflow of GAP-RSS
(1) Install Workflow, QUIP, AIRSS... (no error report as fas as I know)
(2) Prepare inputs as the manual "https://libatoms.github.io/workflow/workflows.rss.html", I got the input file `LiCu.json` from example/gap-rss/LiCu. And edit `length_scales.yaml` as the instruction, however, I got an error report as shown below, while run 

`gap_rss_iter_fit --configuration LiCu.json prep >> gap_rss.prep.out`

```
(wfl) mncui@raven02:LiCu$ gap_rss_iter_fit --configuration LiCu.json prep >> gap_rss.prep.out

LOG 2023-01-26 10:55:58: GAP_RSS_ITER_FIT STARTING, code version git 3d51a83


LOG 2023-01-26 10:55:58: GAP_RSS_ITER_FIT DOING STEP prep

LOG 2023-01-26 10:55:58: Zs array([29])
Traceback (most recent call last):
  File "/u/mncui/.local/bin/gap_rss_iter_fit", line 33, in <module>
    sys.exit(load_entry_point('wfl', 'console_scripts', 'gap_rss_iter_fit')())
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/raven/u/mncui/software/Python/resources/workflow/wfl/cli/gap_rss_iter_fit.py", line 174, in prep
    wfl.generate.buildcell.create_input(
TypeError: create_input() got an unexpected keyword argument 'filename'
```

I was trying to find which filename i defined wrongly, but failed. Do you know what's the possible reason for this error?

Or just because i'm stupidly overlooking something.

Any clue or advice would be Glad for me.

**Comment by MengnanCui** [comment]
BTW, here are the files I referred to: https://thcloud.rz-berlin.mpg.de/s/RaFbsyfWsF7W3MM

**Comment by bernstei** [comment]
I had forgotten to update gap_rss_iter_fit for the latest changes in the rest of the workflow.  I'm working on updating that right now.  Should be ready soon.

**Comment by bernstei** [comment]
Try the latest version.  Merged PR https://github.com/libAtoms/workflow/pull/212 should fix this issue.

**Comment by MengnanCui** [comment]
Great, you are my saver! It works perfectly now! Thank you.
