### ISSUE TITLE
Error encountered when trying to evaluate with GAP in cluster. 

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#252]
Hello, 
I'm playing around with workflow package these days and experimenting few things to implement global optimization with minima hopping. 
At first I started using local workstation which has over 30 cores and parallelization worked pretty fine in this configuration. 
After having seen that workflow package works fine there, I wanted to run this on remote HPC. 
However, unlike local workstation, it's causing following error. 
I wonder if the developers have ever seen this kind of error and have any idea to resolve this problem. 
Also I have attached needed files for execution. 
Many thanks in advance!

Best regards,
Hyunwook 

```
Running wfl.calculators.generic._run_autopara_wrappable with num_python_subprocesses=8, num_inputs_per_python_subprocess=1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/u/hjung/conda-envs/quip/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/pool.py", line 61, in _wrapped_autopara_wrappable
    outputs = op(*u_args, **kwargs)
TypeError: _run_autopara_wrappable() got an unexpected keyword argument 'def_autopara_info'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raven/u/hjung/1_ML/5_workflow/batch_gap_fit.py", line 1086, in <module>
    main(verbose=True)
  File "/raven/u/hjung/1_ML/5_workflow/batch_gap_fit.py", line 964, in main
    train_error = get_ref_error(training, None, files["gap"], train_error=True)
  File "/raven/u/hjung/1_ML/5_workflow/batch_gap_fit.py", line 119, in get_ref_error
    calc_in_config = generic_calc(in_config, OutputSpec(), calculator, output_prefix='calc_')
  File "/raven/u/hjung/Softwares/workflow1/wfl/calculators/generic.py", line 91, in run
    return autoparallelize(_run_autopara_wrappable, *args, def_autopara_info=def_autopara_info, **kwargs)
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/base.py", line 177, in autoparallelize
    return _autoparallelize_ll(autopara_info.num_python_subprocesses, autopara_info.num_inputs_per_python_subprocess,
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/base.py", line 249, in _autoparallelize_ll
    out = do_in_pool(num_python_subprocesses, num_inputs_per_python_subprocess, iterable, outputspec, op, iterable_arg,
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/pool.py", line 154, in do_in_pool
    for result_group in results:
  File "/u/hjung/conda-envs/quip/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: _run_autopara_wrappable() got an unexpected keyword argument 'def_autopara_info'
```
[compress.tar.gz](https://github.com/libAtoms/workflow/files/11999738/compress.tar.gz)

**Comment by bernstei** [comment]
The most obvious way to have an error like this is to have a different version of wfl/expyre on the remote machine.  Can you check that?  It might be useful to add an automated test for that, I guess.

**Comment by gelzinyte** [comment]
Could it be that the wfl version on your local machine and remote cluster are different? I see in PR #248 that you have renamed `default_autopara_info` to `def_autopara_info` in `wfl.calculators.generic`. If you used a git branch with your changes locally, but a fresh installation on the remote machine, the remotely would be given `def_autopara_info`, but not recognise it, because it would expect a `default_atuopara_info`.

**Comment by jungsdao** [comment]
Thank you for the comments, like Elena pointed out, somehow it was messed up with  `default_autoparo_info`. I've updated according to recent version and it seems above mentioned problem has been resolved. 
Thank you!
