### ISSUE TITLE
error in configset

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#299]
I'm getting an error which I haven't seen before, so probably something has gone bad during recent updates in configset. 
Remote job has been successful, but it is not transferred as expected. 

```
134 Traceback (most recent call last):
135   File "*******l/production_md.py", line 235, in <module>
136     run_md(initial_structures, outfile, mace_file, cluster="cobra2", **md_params)
137   File "/home/hjung/Calculation/4_Free_energy_calculation/umbrella_sampling_wfl/production_md.py", line 162, in run_md
138     sample_md(in_config, out_config, calculator=calculator,
139   File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/generate/md/__init__.py", line 267, in md
140     return autoparallelize(_sample_autopara_wrappable, *args,
141            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
142   File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 174, in autoparallelize
143     return _autoparallelize_ll(autopara_info, inputs, outputs, func, *args, **kwargs)
144            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
145   File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 228, in _autoparallelize_ll
146     out = do_remotely(autopara_info, iterable, outputspec, op, rng=rng_op, args=args, kwargs=kwargs,
147           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
148   File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/remote.py", line 160, in do_remotely
149     for at in ats_out.groups():
150   File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/configset.py", line 340, in groups
151     yield ConfigSet(item, _enclosing_loc=self._enclosing_loc + ConfigSet._loc_sep + str(item_i))
152                                          ^^^^^^^^^^^^^^^^^^^
153 AttributeError: 'ConfigSet' object has no attribute '_enclosing_loc'
```

**Comment by bernstei** [comment]
Yes, that's something I added recently. Any chance you have the local and remote versions of wfl not both updated to the latest?

**Comment by jungsdao** [comment]
I have checked again and actually it doesn't give error after making sure that versions are consistent.
I'll close the issue.
