### ISSUE TITLE
Error related to profile 

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#312]
I think profile part in ASE is still in development and after updating to the newest wfl version, I'm still getting error related to profile.
I'm using both newest version of WFL and ASE. 
This is still happening with `"calculator_exec" : "srun /u/hjung/Softwares/QE/qe-7.0/bin/pw.x"` keyword included in the Quantum espresso keywords. 

```
  warnings.warn(f'calculation failed with exception {exc}\n{traceback.format_exc()}')
Gathering results for eval_dft_chunk_1_Mf8qIb5IoPDaZ-RowWbiC8Pr40Luj5Evi_L8JQbGV2w=_ex3mlmpo remote 11051491
Running wfl.calculators.generic._run_autopara_wrappable with num_python_subprocesses=72, num_inputs_per_python_subprocess=10
/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/wfl/calculators/generic.py:123: UserWarning: calculation failed with exception Command '['srun', '/u/hjung/Softwares/QE/qe-7.0/bin/pw.x', '-in', 'espresso.pwi']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/wfl/calculators/generic.py", line 111, in _run_autopara_wrappable
    at.calc.calculate(at, properties=properties_use, system_changes=all_changes)
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/wfl/calculators/espresso.py", line 149, in calculate
    raise exc
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/wfl/calculators/espresso.py", line 139, in calculate
    super().calculate(atoms=atoms, properties=properties, system_changes=system_changes)
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/ase/calculators/genericfileio.py", line 385, in calculate
    self.template.execute(self.directory, self.profile)
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/ase/calculators/espresso.py", line 90, in execute
    profile.run(directory, self.inputname, self.outputname,
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/ase/calculators/genericfileio.py", line 145, in run
    check_call(
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['srun', '/u/hjung/Softwares/QE/qe-7.0/bin/pw.x', '-in', 'espresso.pwi']' returned non-zero exit status 1.

  warnings.warn(f'calculation failed with exception {exc}\n{traceback.format_exc()}')
```

**Comment by jungsdao** [comment]
There was stupid mistake from my side. 
I"ll close this issue. Sorry for inconvenience.

**Comment by bernstei** [comment]
Glad it's actually working.  Maybe once ASE stabilizes, and starts releasing versions with different numbers, we'll be able to settle on a single well defined interface to the calculators.
