### ISSUE TITLE
copying back generated logfile

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#331]
Thanks to #327, now I can generate MD logfile simultaneously with simulation. However, currently copying back generated logfile from remote to local machine via `ExPyRe` `output_files=["cvlog.item_*"]` doesn't seem to work. It has failed with following error message. 

```
Creating job production_md_chunk_0
ExPyRe production_md_chunk_0 constructor done stage in files 1722974388.7874625
Starting job for production_md_chunk_0_8WBrLI6mAEeX86d98in_8-cwadTFv2Wr3JHNDJERmUc=_qi6__tvv
Gathering results for production_md_chunk_0_8WBrLI6mAEeX86d98in_8-cwadTFv2Wr3JHNDJERmUc=_qi6__tvv remote 12272477
Waiting for job production_md_chunk_0_8WBrLI6mAEeX86d98in_8-cwadTFv2Wr3JHNDJERmUc=_qi6__tvv up to 86400 s: 
qqrr/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/remote.py:141: UserWarning: Failed in remote job production_md_chunk_0_8WBrLI6mAEeX86d98in_8-cwadTFv2Wr3JHNDJERmUc=_qi6__tvv on raven_gpu
  warnings.warn(f'Failed in remote job {xpr.id} on {xpr.system_name}')
Traceback (most recent call last):
  File "/work/home/hjung/Calculation/6_Universal_MACE/4_Umbrella_sampling/iter_0/production_md_2D.py", line 226, in <module>
    run_md(traj, outfile, mace_file, cluster=args.remote, **md_params)
  File "/work/home/hjung/Calculation/6_Universal_MACE/4_Umbrella_sampling/iter_0/production_md_2D.py", line 151, in run_md
    sample_md(in_config, out_config, calculator=calculator,
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/generate/md/__init__.py", line 294, in md
    return autoparallelize(_sample_autopara_wrappable, *args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 174, in autoparallelize
    return _autoparallelize_ll(autopara_info, inputs, outputs, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 228, in _autoparallelize_ll
    out = do_remotely(autopara_info, iterable, outputspec, op, rng=rng_op, args=args, kwargs=kwargs,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/remote.py", line 135, in do_remotely
    ats_out, stdout, stderr = xpr.get_results(timeout=remote_info.timeout, check_interval=remote_info.check_interval)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/expyre/func.py", line 756, in get_results
    ExPyRe._copy(self.stage_dir, Path.cwd(), in_file)
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/expyre/func.py", line 350, in _copy
    raise RuntimeError(f'File glob "{file_glob}" (excluding {exclude_glob}) in input_files does not match any files')
RuntimeError: File glob "cvlog.item_*" (excluding None) in input_files does not match any files
```

**Comment by jungsdao** [comment]
There was mistake from my side. sorry for confusion!
